---
- name: BACKUP ROUTER CONFIGURATIONS
  hosts: cisco
  connection: network_cli
  gather_facts: no

  vars:
    backupdir: /tmp/backup

  tasks:
    - name: BACKUP THE CONFIG
      ios_config:
        backup: yes
      register: config_output

    - name: CREATE BACKUPS DIRECTORY
      file:
        path: "{{backupdir}}"
        state: directory
      delegate_to: localhost

    - name: RENAME BACKUP
      copy:
        src: "{{config_output.backup_path}}"
        dest: "{{backupdir}}/{{inventory_hostname}}.config"

    - name: REMOVE NON CONFIG LINES
      lineinfile:
        path: "{{backupdir}}/{{inventory_hostname}}.config"
        line: "Building configuration..."
        state: absent

    - name: REMOVE NON CONFIG LINES - REGEXP
      lineinfile:
        path: "{{backupdir}}/{{inventory_hostname}}.config"
        regexp: 'Current configuration.*'
        state: absent
