---
- name: Add VLANS to router config
  hosts: cisco
  gather_facts: no
  connection: network_cli

  vars:
    vlan_id: "100"

  tasks:

    - name: Create vlan
      ios_vlan:
        vlan_id: "{{vlan_id}}"
        name: test-vlan
        state: present

    - name: Add interfaces to VLAN
      ios_vlan:
        vlan_id: "{{vlan_id}}"
        interfaces:
          - GigabitEthernet0/0
          - GigabitEthernet0/1

    - name: Check if interfaces is assigned to VLAN
      ios_vlan:
        vlan_id: "{{vlan_id}}"
        associated_interfaces:
          - GigabitEthernet0/0
          - GigabitEthernet0/1
