---
- name: CONFIGURE INTERFACES
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: SET IP ADDRESS
      ios_l3_interface:
        name: Tunnel1
        ipv4: 192.168.0.5/24
        ipv6: dhcp

