---
- name: CHANGE USER CREDENTIALS
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: CHANGE USERS PASSWORD
      ios_user:
        name: "{{net_username}}"
        configured_password: "{{ net_new_password }}"
        update_password: always
        state: present

