- name: TOWER CONFIGURATION WITH PLAYBOOKS
  hosts: ansible
  connection: local
  gather_facts: no
  become: no

  pre_tasks:

    - name: Get student number (needed for SSH key)
      command: /usr/bin/whoami
      register: whoami

  tasks:

    - name: CREATE INVENTORY
      tower_inventory:
        name: "Workshop Inventory"
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        tower_verify_ssl: no

    - name: ADD CONTROL HOST INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        tower_verify_ssl: no
        variables:
          ansible_host: "{{ansible_host}}"
          ansible_user: "ec2-user"
          private_ip: "{{private_ip}}"
          ansible_connection: ssh


    - name: ADD REPO INTO TOWER
      tower_project:
        name: "Workshop Project"
        organization: "Default"
        scm_type: git
        scm_url: "https://github.com/network-automation/tower_workshop"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        tower_verify_ssl: no
      run_once: true
      delegate_to: localhost

    - name: ADD REPO INTO TOWER
      tower_project:
        name: "Phils Example Networking Demos"
        organization: "Default"
        scm_type: git
        scm_url: "https://github.com/ffirg/ansible-networking"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        tower_verify_ssl: no
      run_once: true
      delegate_to: localhost

    - name: ADD CREDENTIAL INTO TOWER
      tower_credential:
        name: Workshop Credential
        ssh_key_data: "/home/{{whoami.stdout}}/.ssh/aws-private.pem"
        kind: ssh
        organization: Default
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        tower_verify_ssl: no

- name: ADD EACH HOST TO INVENTORY
  hosts: routers
  connection: local
  become: yes
  gather_facts: no
  tasks:

    - name: ADD HOST INTO TOWER
      tower_host:
        name: "{{ inventory_hostname }}"
        inventory: "Workshop Inventory"
        tower_username: admin
        tower_password: ansible
        tower_host: https://localhost
        tower_verify_ssl: no
        variables:
          ansible_network_os: "{{ansible_network_os}}"
          ansible_host: "{{ansible_host}}"
          ansible_user: "{{ansible_user}}"
          private_ip: "{{private_ip}}"
          ansible_connection: network_cli
          ansible_become: yes
          #ansible_become_method: enable


